package roburrito.fantasticcreatures.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import org.lwjgl.opengl.GL11;

/**
 * Equine by Unknown
 */
@SideOnly(Side.CLIENT)
public class ModelEquine extends ModelBase {
    public ModelRenderer Hip;
    public ModelRenderer shoulder;
    public ModelRenderer wing;
    public ModelRenderer wingulna;
    public ModelRenderer wingtip;
    public ModelRenderer wingtipskin;
    public ModelRenderer wingskin;
    public ModelRenderer bicep;
    public ModelRenderer foreleg;
    public ModelRenderer hooffront;
    public ModelRenderer neck;
    public ModelRenderer brow;
    public ModelRenderer browhorn;
    public ModelRenderer muzzle;
    public ModelRenderer muzzlehorn;
    public ModelRenderer mouth;
    public ModelRenderer mane;
    public ModelRenderer ear;
    public ModelRenderer belly;
    public ModelRenderer saddle;
    public ModelRenderer saddlestrap;
    public ModelRenderer saddlestirrup;
    public ModelRenderer tail;
    public ModelRenderer tailtail;
    public ModelRenderer tailtip;
    public ModelRenderer swim1;
    public ModelRenderer swim2;
    public ModelRenderer swim3;
    public ModelRenderer swimfin;
    public ModelRenderer fin;
    public ModelRenderer thigh;
    public ModelRenderer cannon;
    public ModelRenderer hoofrear;
    public ModelRenderer chest;

    public ModelEquine() {
        this.textureWidth = 128;
        this.textureHeight = 128;

        this.Hip = new ModelRenderer(this, 1, 109);
        this.Hip.setRotationPoint(0.0F, 11.0F, 10.0F);
        this.Hip.addBox(-5.0F, -8.0F, -4.0F, 10, 10, 8);
        this.shoulder = new ModelRenderer(this, 1, 71);
        this.shoulder.setRotationPoint(0.0F, -6.0F, -15.0F);
        this.shoulder.addBox(-5.0F, -2.0F, -5.0F, 10, 10, 8);
        this.Hip.addChild(this.shoulder);
        this.wing = new ModelRenderer(this, 37, 82);
        this.wing.setRotationPoint(-5.0F, 0.0F, 0.0F);
        this.wing.addBox(-5.0F, -1.5F, -1.5F, 5, 3, 3);
        this.setRotationAngles(this.wing, 0.0F, 0.2617993877991494F, 0.17453292519943295F);
        this.shoulder.addChild(this.wing);
        this.wingulna = new ModelRenderer(this, 37, 76);
        this.wingulna.setRotationPoint(-5.0F, 0.0F, 0.0F);
        this.wingulna.addBox(-16.0F, -1.5F, -1.5F, 16, 3, 3);
        this.setRotationAngles(this.wingulna, 0.0F, -0.5235987755982988F, -0.3490658503988659F);
        this.wing.addChild(this.wingulna);
        this.wingtip = new ModelRenderer(this, 38, 72);
        this.wingtip.setRotationPoint(-16.0F, 0.0F, 0.0F);
        this.wingtip.addBox(-12.0F, -1.0F, -1.0F, 12, 2, 2);
        this.setRotationAngles(this.wingtip, 0.0F, 0.7853981633974483F, -0.17453292519943295F);
        this.wingulna.addChild(this.wingtip);
        this.wingtipskin = new ModelRenderer(this, 68, 104);
        this.wingtipskin.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.wingtipskin.addBox(-16.0F, -0.5F, -0.5F, 16, 0, 12);
        this.wingtip.addChild(this.wingtipskin);
        this.wingskin = new ModelRenderer(this, 64, 116);
        this.wingskin.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.wingskin.addBox(-19.0F, -1.0F, 0.9F, 20, 0, 12);
        this.wingulna.addChild(this.wingskin);
        this.bicep = new ModelRenderer(this, 54, 111);
        this.bicep.setRotationPoint(-4.0F, 3.0F, -1.5F);
        this.bicep.addBox(-2.0F, 0.0F, -1.5F, 4, 6, 4);
        this.shoulder.addChild(this.bicep);
        this.foreleg = new ModelRenderer(this, 56, 101);
        this.foreleg.setRotationPoint(0.0F, 6.0F, 1.5F);
        this.foreleg.addBox(-1.5F, 0.0F, -2.0F, 3, 7, 3);
        this.bicep.addChild(this.foreleg);
        this.hooffront = new ModelRenderer(this, 38, 121);
        this.hooffront.setRotationPoint(0.0F, 7.0F, -1.0F);
        this.hooffront.addBox(-2.0F, 0.0F, -3.0F, 4, 3, 4);
        this.foreleg.addChild(this.hooffront);
        this.neck = new ModelRenderer(this, 7, 49);
        this.neck.setRotationPoint(0.0F, -2.0F, -5.0F);
        this.neck.addBox(-2.0F, -9.8F, -2.0F, 4, 14, 8);
        this.setRotationAngles(this.neck, 0.5235987755982988F, 0.0F, 0.0F);
        this.shoulder.addChild(this.neck);
        this.brow = new ModelRenderer(this, 7, 37);
        this.brow.setRotationPoint(0.0F, -10.0F, 0.0F);
        this.brow.addBox(-2.5F, 0.0F, -1.5F, 5, 5, 7);
        this.neck.addChild(this.brow);
        this.browhorn = new ModelRenderer(this, 2, 43);
        this.browhorn.setRotationPoint(0.0F, 0.0F, 2.0F);
        this.browhorn.addBox(-0.5F, 0.0F, -0.5F, 1, 5, 1);
        this.setRotationAngles(this.browhorn, 3.141592653589793F, 0.0F, 0.0F);
        this.brow.addChild(this.browhorn);
        this.muzzle = new ModelRenderer(this, 10, 29);
        this.muzzle.setRotationPoint(0.0F, -9.8F, -2.0F);
        this.muzzle.addBox(-2.0F, 0.0F, -5.0F, 4, 3, 5);
        this.neck.addChild(this.muzzle);
        this.muzzlehorn = new ModelRenderer(this, 2, 43);
        this.muzzlehorn.setRotationPoint(0.0F, 0.0F, -2.5F);
        this.muzzlehorn.addBox(-0.5F, 0.0F, -0.5F, 1, 3, 1);
        this.setRotationAngles(this.muzzlehorn, 3.141592653589793F, 0.0F, 0.0F);
        this.muzzle.addChild(this.muzzlehorn);
        this.mouth = new ModelRenderer(this, 11, 23);
        this.mouth.setRotationPoint(0.0F, -6.8F, -2.0F);
        this.mouth.addBox(-1.5F, 0.0F, -4.5F, 3, 2, 5);
        this.neck.addChild(this.mouth);
        this.mane = new ModelRenderer(this, 31, 51);
        this.mane.setRotationPoint(0.0F, 4.0F, 0.0F);
        this.mane.addBox(-1.0F, -16.0F, 5.0F, 2, 16, 4);
        this.neck.addChild(this.mane);
        this.ear = new ModelRenderer(this, 32, 45);
        this.ear.setRotationPoint(-0.5F, -10.0F, 4.0F);
        this.ear.addBox(-2.0F, -3.0F, -0.5F, 2, 3, 1);
        this.neck.addChild(this.ear);
        this.belly = new ModelRenderer(this, 0, 89);
        this.belly.setRotationPoint(0.0F, -5.5F, -8.0F);
        this.belly.addBox(-4.5F, -2.0F, -5.0F, 9, 10, 10);
        this.Hip.addChild(this.belly);
        this.saddle = new ModelRenderer(this, 43, 90);
        this.saddle.setRotationPoint(0.0F, -3.0F, 0.0F);
        this.saddle.addBox(-5.0F, 0.0F, -3.0F, 10, 1, 8);
        this.belly.addChild(this.saddle);
        this.saddlestrap = new ModelRenderer(this, 38, 88);
        this.saddlestrap.setRotationPoint(-5.0F, 1.0F, 0.0F);
        this.saddlestrap.addBox(-0.5F, 0.0F, -0.5F, 1, 6, 1);
        this.saddle.addChild(this.saddlestrap);
        this.saddlestirrup = new ModelRenderer(this, 37, 95);
        this.saddlestirrup.setRotationPoint(-5.0F, 1.0F, 0.0F);
        this.saddlestirrup.addBox(-0.5F, 6.0F, -1.0F, 1, 2, 2);
        this.saddle.addChild(this.saddlestirrup);
        this.tail = new ModelRenderer(this, 87, 60);
        this.tail.setRotationPoint(0.0F, -8.0F, 4.0F);
        this.tail.addBox(-1.0F, -1.0F, 0.0F, 2, 2, 3);
        this.setRotationAngles(this.tail, -1.3089969389957472F, 0.0F, 0.0F);
        this.Hip.addChild(this.tail);
        this.tailtail = new ModelRenderer(this, 82, 65);
        this.tailtail.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.tailtail.addBox(-1.5F, -2.0F, 3.0F, 3, 4, 7);
        this.tail.addChild(this.tailtail);
        this.tailtip = new ModelRenderer(this, 82, 76);
        this.tailtip.setRotationPoint(0.0F, 0.0F, 9.0F);
        this.tailtip.addBox(-1.5F, -2.0F, 0.0F, 3, 4, 7);
        this.setRotationAngles(this.tailtip, -0.2617993877991494F, 0.0F, 0.0F);
        this.tailtail.addChild(this.tailtip);
        this.swim1 = new ModelRenderer(this, 96, 0);
        this.swim1.setRotationPoint(0.0F, -6.5F, 4.0F);
        this.swim1.addBox(-4.0F, -1.0F, -1.0F, 8, 8, 8);
        this.setRotationAngles(this.swim1, -0.3490658503988659F, 0.0F, 0.0F);
        this.Hip.addChild(this.swim1);
        this.swim2 = new ModelRenderer(this, 98, 16);
        this.swim2.setRotationPoint(0.0F, 0.5F, 6.0F);
        this.swim2.addBox(-3.0F, -1.0F, 0.0F, 6, 6, 8);
        this.setRotationAngles(this.swim2, -0.3490658503988659F, 0.0F, 0.0F);
        this.swim1.addChild(this.swim2);
        this.swim3 = new ModelRenderer(this, 98, 30);
        this.swim3.setRotationPoint(0.0F, 0.5F, 6.0F);
        this.swim3.addBox(-2.0F, -1.0F, 0.0F, 4, 3, 10);
        this.setRotationAngles(this.swim3, -0.3490658503988659F, 0.0F, 0.0F);
        this.swim2.addChild(this.swim3);
        this.swimfin = new ModelRenderer(this, 100, 43);
        this.swimfin.setRotationPoint(0.0F, 0.0F, 10.0F);
        this.swimfin.addBox(-8.0F, 0.0F, -4.0F, 8, 1, 4);
        this.setRotationAngles(this.swimfin, 0.0F, 0.2617993877991494F, -0.17453292519943295F);
        this.swim3.addChild(this.swimfin);
        this.fin = new ModelRenderer(this, 78, 0);
        this.fin.setRotationPoint(0.0F, -8.0F, 0.0F);
        this.fin.addBox(-0.5F, -6.0F, -2.5F, 1, 6, 8);
        this.Hip.addChild(this.fin);
        this.thigh = new ModelRenderer(this, 38, 99);
        this.thigh.setRotationPoint(-4.0F, 9.0F, 11.0F);
        this.thigh.addBox(-2.0F, -2.0F, -3.5F, 4, 7, 5);
        this.cannon = new ModelRenderer(this, 40, 111);
        this.cannon.setRotationPoint(0.0F, 5.0F, 0.0F);
        this.cannon.addBox(-1.5F, 0.0F, 0.0F, 3, 7, 3);
        this.thigh.addChild(this.cannon);
        this.hoofrear = new ModelRenderer(this, 38, 121);
        this.hoofrear.setRotationPoint(0.0F, 7.0F, 1.0F);
        this.hoofrear.addBox(-2.0F, 0.0F, -3.0F, 4, 3, 4);
        this.cannon.addChild(this.hoofrear);
        this.chest = new ModelRenderer(this, 81, 89);
        this.chest.setRotationPoint(-7.5F, 2.5F, 10.0F);
        this.chest.addBox(-3.0F, 0.0F, 0.0F, 8, 8, 3);
        this.setRotationAngles(this.chest, 0.0F, 1.5707963267948966F, 0.0F);
    }

    @Override
    public void render(Entity entity, float limbSwing, float limbSwingAmount, float ageInTicks, float rotationYaw, float rotationPitch, float scale) {
        GlStateManager.enableBlend();
        GlStateManager.blendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA);
        GlStateManager.color(1.0F, 1.0F, 1.0F, 0.0F);
        this.Hip.render(scale);
        GlStateManager.disableBlend();
        GlStateManager.enableBlend();
        GlStateManager.blendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA);
        GlStateManager.color(1.0F, 1.0F, 1.0F, 0.0F);
        this.thigh.render(scale);
        GlStateManager.disableBlend();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.chest.offsetX, this.chest.offsetY, this.chest.offsetZ);
        GlStateManager.translate(this.chest.rotationPointX * scale, this.chest.rotationPointY * scale, this.chest.rotationPointZ * scale);
        GlStateManager.scale(1.0F, 1.0F, 1.0F);
        GlStateManager.translate(-this.chest.offsetX, -this.chest.offsetY, -this.chest.offsetZ);
        GlStateManager.translate(-this.chest.rotationPointX * scale, -this.chest.rotationPointY * scale, -this.chest.rotationPointZ * scale);
        GlStateManager.enableBlend();
        GlStateManager.blendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA);
        GlStateManager.color(1.0F, 1.0F, 1.0F, 0.0F);
        this.chest.render(scale);
        GlStateManager.disableBlend();
        GlStateManager.popMatrix();
    }

    public void setRotationAngles(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }
}
